### ISSUE TITLE
hello 我也正在看scrcpy的源码，请问你的APPRemote优势在哪里？

### ISSUE THREAD

**Issue by freedomofme** [deepsadness/AppRemote#1]

**Comment by deepsadness** [comment]
> _No description provided._

你好。
scrcpy写的比较好，很感谢作者的分享。
我就是学习他的。
介绍里面说了，我就是对着它撸了一遍。
你可以理解成一个极简化的版本吧。

**Comment by freedomofme** [comment]
好的，谢谢。
对了，请问下，反射InputManager这样的代码，好像只有在adb 中的dex中才能执行。在正常安装的APK里面是不行的，是吗？

**Comment by deepsadness** [comment]
> 好的，谢谢。
> 对了，请问下，反射InputManager这样的代码，好像只有在adb 中的dex中才能执行。在正常安装的APK里面是不行的，是吗？

反射的代码都是可以用的。
但是需要注意的是：只有获取截屏的Surface，需要获取权限之后，才能使用。
